stages:
  - build
  - deploy

build:  
  pages:
    image: alpine:latest
    stage: deploy
    variables:
      PUBLIC_URL: https://hangerthem.gitlab.io/math-training-app/ 
      GIT_STRATEGY: none
    script:
      - mv build public         
    artifacts:
      paths:
        - public